with

source as (

    select * from {{ source('shopify', 'orders') }}

),

orders as (

    select
        id as order_id,
        checkout_id,
        user_id,
        json_value(customer, '$.id') as customer_id,
        device_id,
        location_id,
        app_id,
        merchant_of_record_app_id,
        confirmation_number,
        fulfillment_status,
        to_json(original_total_additional_fees_set) as original_total_additional_fees_set,
        cast(total_price_usd as FLOAT64) as total_price_usd,
        to_json(current_total_discounts_set) as current_total_discounts_set,
        to_json(billing_address) as billing_address,
        to_json(line_items) as line_items,
        to_json(total_discounts_set) as total_discounts_set,
        presentment_currency,
        original_total_duties_set,
        source_url,
        landing_site,
        source_identifier,
        reference,
        number,
        to_json(tax_lines) as tax_lines,
        checkout_token,
        cast(current_total_discounts as FLOAT64) as current_total_discounts,
        customer_locale,
        to_json(current_total_additional_fees_set) as current_total_additional_fees_set,
        cast(subtotal_price as FLOAT64) as subtotal_price,
        order_status_url,
        test,
        to_json(current_total_price_set) as current_total_price_set,
        to_json(total_shipping_price_set) as total_shipping_price_set,
        tax_exempt,
        to_json(subtotal_price_set) as subtotal_price_set,
        to_json(payment_gateway_names) as payment_gateway_names,
        cast(total_tax as FLOAT64) as total_tax,
        to_json(discount_allocations) as discount_allocations,
        tags,
        to_json(current_subtotal_price_set) as current_subtotal_price_set,
        to_json(shipping_lines) as shipping_lines,
        cast(current_total_tax as FLOAT64) as current_total_tax,
        phone,
        to_json(note_attributes) as note_attributes,
        name,
        cart_token,
        to_json(total_tax_set) as total_tax_set,
        landing_site_ref,
        to_json(discount_codes) as discount_codes,
        note,
        estimated_taxes,
        to_json(current_total_tax_set) as current_total_tax_set,
        cast(current_subtotal_price as FLOAT64) as current_subtotal_price,
        cast(total_outstanding as FLOAT64) as total_outstanding,
        order_number,
        to_json(discount_applications) as discount_applications,
        to_json(total_line_items_price_set) as total_line_items_price_set,
        taxes_included,
        payment_terms,
        buyer_accepts_marketing,
        confirmed,
        total_weight,
        to_json(refunds) as refunds,
        contact_email,
        cast(total_discounts as FLOAT64) as total_discounts,
        to_json(fulfillments) as fulfillments,
        po_number,
        to_json(client_details) as client_details,
        referring_site,
        shop_url,
        company,
        currency,
        to_json(shipping_address) as shipping_address,
        email,
        browser_ip,
        source_name,
        to_json(total_price_set) as total_price_set,
        cast(total_price as FLOAT64) as total_price,
        current_total_duties_set,
        cast(total_line_items_price as FLOAT64) as total_line_items_price,
        cast(total_tip_received as FLOAT64) as total_tip_received,
        token,
        cancel_reason,
        cast(current_total_price as FLOAT64) as current_total_price,
        financial_status,
        admin_graphql_api_id,
        to_json(customer) as customer,
        processed_at,
        closed_at,
        cancelled_at,
        created_at,
        updated_at

    from source

)

select * from orders